
var npiet = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(npiet) {
  npiet = npiet || {};


var c;c||(c=typeof npiet !== 'undefined' ? npiet : {});var aa,ba;c.ready=new Promise(function(a,b){aa=a;ba=b});var h={},p;for(p in c)c.hasOwnProperty(p)&&(h[p]=c[p]);var ca=[],da="./this.program";function ea(a,b){throw b;}var u="",fa,ha;"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src);_scriptDir&&(u=_scriptDir);0!==u.indexOf("blob:")?u=u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):u="";
fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};ha=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)};var v=c.print||console.log.bind(console),x=c.printErr||console.warn.bind(console);for(p in h)h.hasOwnProperty(p)&&(c[p]=h[p]);h=null;c.arguments&&(ca=c.arguments);c.thisProgram&&(da=c.thisProgram);c.quit&&(ea=c.quit);
function ia(a){ja||(ja={});ja[a]||(ja[a]=1,x(a))}var ja,ka=0,y;c.wasmBinary&&(y=c.wasmBinary);var noExitRuntime=c.noExitRuntime||!1;"object"!==typeof WebAssembly&&z("no native wasm support detected");var la,A=!1,ma;function na(a,b){a||z("Assertion failed: "+b)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function B(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&oa)return oa.decode(a.subarray(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}
function pa(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(d>=e)break;b[d++]=k}else{if(2047>=k){if(d+1>=e)break;b[d++]=192|k>>6}else{if(65535>=k){if(d+2>=e)break;b[d++]=224|k>>12}else{if(d+3>=e)break;b[d++]=240|k>>18;b[d++]=128|k>>12&63}b[d++]=128|k>>6&63}b[d++]=128|k&63}}b[d]=0;return d-f}
function ra(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function sa(a){var b=ra(a)+1,d=ta(b);pa(a,C,d,b);return d}var ua,C,va,wa,D,xa,ya,za=[],Aa=[],Ba=[],Ca=[],Da=[],Ea=!1,E=0;function Fa(){var a=c.preRun.shift();za.unshift(a)}var F=0,Ga=null,G=null;function Ha(){F++;c.monitorRunDependencies&&c.monitorRunDependencies(F)}
function H(){F--;c.monitorRunDependencies&&c.monitorRunDependencies(F);if(0==F&&(null!==Ga&&(clearInterval(Ga),Ga=null),G)){var a=G;G=null;a()}}c.preloadedImages={};c.preloadedAudios={};function z(a){if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";x(a);A=!0;ma=1;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ia(){return I.startsWith("data:application/octet-stream;base64,")}var I;I="npiet.wasm";
if(!Ia()){var Ja=I;I=c.locateFile?c.locateFile(Ja,u):u+Ja}function Ka(){var a=I;try{if(a==I&&y)return new Uint8Array(y);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}function La(){return y||"function"!==typeof fetch?Promise.resolve().then(function(){return Ka()}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Ka()})}var J,Ma;
function Na(a,b){Oa=a;Pa=b;if(L)if(Qa||(E+=1,Qa=!0),0==a)M=function(){var e=Math.max(0,Ra+b-Sa())|0;setTimeout(N,e)};else if(1==a)M=function(){Ta(N)};else if(2==a){if("undefined"===typeof setImmediate){var d=[];addEventListener("message",function(e){if("setimmediate"===e.data||"setimmediate"===e.data.target)e.stopPropagation(),d.shift()()},!0);setImmediate=function(e){d.push(e);postMessage("setimmediate","*")}}M=function(){setImmediate(N)}}}var Sa;Sa=function(){return performance.now()};
function Ua(a){a instanceof Va||"unwind"==a||ea(1,a)}function Wa(){if(!(noExitRuntime||0<E))try{Xa(ma)}catch(a){Ua(a)}}
function Ya(a){function b(){return d<Za?(--E,Wa(),!1):!0}na(!L,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");L=a;var d=Za;Qa=!1;N=function(){if(!A)if(0<$a.length){var e=Date.now(),f=$a.shift();f.Hb(f.ta);if(ab){var g=ab,k=0==g%1?g-1:Math.floor(g);ab=f.hc?k:(8*g+(k+.5))/9}v('main loop blocker "'+f.name+'" took '+(Date.now()-e)+" ms");c.setStatus&&(e=c.statusMessage||
"Please wait...",f=ab,g=bb.lc,f?f<g?c.setStatus(e+" ("+(g-f)+"/"+g+")"):c.setStatus(e):c.setStatus(""));b()&&setTimeout(N,0)}else b()&&(cb=cb+1|0,1==Oa&&1<Pa&&0!=cb%Pa?M():(0==Oa&&(Ra=Sa()),A||c.preMainLoop&&!1===c.preMainLoop()||(db(a),c.postMainLoop&&c.postMainLoop()),b()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Vb&&SDL.audio.Vb(),M())))}}function db(a){if(!Ea&&!A)try{a(),Wa()}catch(b){Ua(b)}}function eb(a){E+=1;setTimeout(function(){--E;db(a)},1E4)}
var Qa=!1,M=null,Za=0,L=null,Oa=0,Pa=0,cb=0,$a=[],bb={},Ra,N,ab,O=!1,fb=!1,gb=[];
function hb(){function a(){fb=document.pointerLockElement===c.canvas||document.mozPointerLockElement===c.canvas||document.webkitPointerLockElement===c.canvas||document.msPointerLockElement===c.canvas}c.preloadPlugins||(c.preloadPlugins=[]);if(!ib){ib=!0;try{P=!0}catch(d){P=!1,v("warning: no blob constructor, cannot create blobs with mimetypes")}jb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:P?null:v("warning: no BlobBuilder");Q="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;c.qb||"undefined"!==typeof Q||(v("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),c.qb=!0);c.preloadPlugins.push({canHandle:function(d){return!c.qb&&/\.(jpg|jpeg|png|bmp)$/i.test(d)},handle:function(d,e,f,g){var k=null;if(P)try{k=new Blob([d],{type:kb(e)}),k.size!==d.length&&(k=new Blob([(new Uint8Array(d)).buffer],{type:kb(e)}))}catch(n){ia("Blob constructor present but fails: "+
n+"; falling back to blob builder")}k||(k=new jb,k.append((new Uint8Array(d)).buffer),k=k.getBlob());var l=Q.createObjectURL(k),m=new Image;m.onload=function(){na(m.complete,"Image "+e+" could not be decoded");var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,0,0);c.preloadedImages[e]=n;Q.revokeObjectURL(l);f&&f(d)};m.onerror=function(){v("Image "+l+" could not be decoded");g&&g()};m.src=l}});c.preloadPlugins.push({canHandle:function(d){return!c.Fc&&
d.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(d,e,f,g){function k(r){m||(m=!0,c.preloadedAudios[e]=r,f&&f(d))}function l(){m||(m=!0,c.preloadedAudios[e]=new Audio,g&&g())}var m=!1;if(P){try{var n=new Blob([d],{type:kb(e)})}catch(r){return l()}n=Q.createObjectURL(n);var q=new Audio;q.addEventListener("canplaythrough",function(){k(q)},!1);q.onerror=function(){if(!m){v("warning: browser could not fully decode audio "+e+", trying slower base64 approach");for(var r="",t=0,w=0,K=0;K<d.length;K++)for(t=
t<<8|d[K],w+=8;6<=w;){var Z=t>>w-6&63;w-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Z]}2==w?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],r+="=="):4==w&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],r+="=");q.src="data:audio/x-"+e.substr(-3)+";base64,"+r;k(q)}};q.src=n;eb(function(){k(q)})}else return l()}});var b=c.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),c.elementPointerLock&&b.addEventListener("click",
function(d){!fb&&c.canvas.requestPointerLock&&(c.canvas.requestPointerLock(),d.preventDefault())},!1))}}
function lb(a,b,d,e){if(b&&c.bb&&a==c.canvas)return c.bb;var f;if(b){var g={antialias:!1,alpha:!1,yc:1};if(e)for(var k in e)g[k]=e[k];if("undefined"!==typeof GL&&(f=GL.ic(a,g)))var l=GL.getContext(f).bc}else l=a.getContext("2d");if(!l)return null;d&&(b||na("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),c.bb=l,b&&GL.zc(f),c.Lc=b,gb.forEach(function(m){m()}),hb());return l}var mb=!1,nb=void 0,R=void 0;
function ob(a,b){function d(){O=!1;var g=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(e.exitFullscreen=pb,nb&&e.requestPointerLock(),O=!0,R?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=xa[SDL.screen>>2]|8388608),qb(c.canvas),rb()):qb(e)):(g.parentNode.insertBefore(e,g),g.parentNode.removeChild(g),R?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=xa[SDL.screen>>2]&-8388609),
qb(c.canvas),rb()):qb(e));if(c.onFullScreen)c.onFullScreen(O);if(c.onFullscreen)c.onFullscreen(O)}nb=a;R=b;"undefined"===typeof nb&&(nb=!0);"undefined"===typeof R&&(R=!1);var e=c.canvas;mb||(mb=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=
f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function pb(){if(!O)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var sb=0;function Ta(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===sb)sb=b+1E3/60;else for(;b+2>=sb;)sb+=1E3/60;setTimeout(a,Math.max(sb-b,0))}}
function kb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var tb=[];function rb(){var a=c.canvas;tb.forEach(function(b){b(a.width,a.height)})}
function qb(a,b,d){b&&d?(a.ac=b,a.Jb=d):(b=a.ac,d=a.Jb);var e=b,f=d;c.forcedAspectRatio&&0<c.forcedAspectRatio&&(e/f<c.forcedAspectRatio?e=Math.round(f*c.forcedAspectRatio):f=Math.round(e/c.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*
g)}R?(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=d&&(a.height=d),"undefined"!=typeof a.style&&(e!=b||f!=d?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var ib,P,jb,Q;
function ub(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(c);else{var d=b.Hb;"number"===typeof d?void 0===b.ta?vb(d)():vb(d)(b.ta):d(void 0===b.ta?null:b.ta)}}}var wb=[];function vb(a){var b=wb[a];b||(a>=wb.length&&(wb.length=a+1),wb[a]=b=ya.get(a));return b}function xb(a,b){for(var d=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),d++):d&&(a.splice(e,1),d--)}if(b)for(;d;d--)a.unshift("..");return a}
function yb(a){var b="/"===a.charAt(0),d="/"===a.substr(-1);(a=xb(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&d&&(a+="/");return(b?"/":"")+a}function zb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function S(a){if("/"===a)return"/";a=yb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function T(a,b){return yb(a+"/"+b)}function Ab(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){z("randomDevice")}}
function U(){for(var a="",b=!1,d=arguments.length-1;-1<=d&&!b;d--){b=0<=d?arguments[d]:V.Fa();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=xb(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function Bb(a,b){function d(k){for(var l=0;l<k.length&&""===k[l];l++);for(var m=k.length-1;0<=m&&""===k[m];m--);return l>m?[]:k.slice(l,m-l+1)}a=U(a).substr(1);b=U(b).substr(1);a=d(a.split("/"));b=d(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var Cb=[];function Db(a,b){Cb[a]={input:[],L:[],fa:b};V.Ua(a,Eb)}
var Eb={open:function(a){var b=Cb[a.node.Ba];if(!b)throw new V.A(43);a.I=b;a.seekable=!1},close:function(a){a.I.fa.flush(a.I)},flush:function(a){a.I.fa.flush(a.I)},read:function(a,b,d,e){if(!a.I||!a.I.fa.kb)throw new V.A(60);for(var f=0,g=0;g<e;g++){try{var k=a.I.fa.kb(a.I)}catch(l){throw new V.A(29);}if(void 0===k&&0===f)throw new V.A(6);if(null===k||void 0===k)break;f++;b[d+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){if(!a.I||!a.I.fa.Ra)throw new V.A(60);try{for(var f=
0;f<e;f++)a.I.fa.Ra(a.I,b[d+f])}catch(g){throw new V.A(29);}e&&(a.node.timestamp=Date.now());return f}},Gb={kb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Fb(b)}return a.input.shift()},Ra:function(a,b){null===b||10===b?(v(B(a.L,0)),a.L=[]):0!=b&&a.L.push(b)},flush:function(a){a.L&&0<a.L.length&&(v(B(a.L,
0)),a.L=[])}},Hb={Ra:function(a,b){null===b||10===b?(x(B(a.L,0)),a.L=[]):0!=b&&a.L.push(b)},flush:function(a){a.L&&0<a.L.length&&(x(B(a.L,0)),a.L=[])}},W={U:null,H:function(){return W.createNode(null,"/",16895,0)},createNode:function(a,b,d,e){if(V.Kb(d)||V.Lb(d))throw new V.A(63);W.U||(W.U={dir:{node:{R:W.B.R,K:W.B.K,aa:W.B.aa,W:W.B.W,ra:W.B.ra,Y:W.B.Y,sa:W.B.sa,qa:W.B.qa,X:W.B.X},stream:{S:W.D.S}},file:{node:{R:W.B.R,K:W.B.K},stream:{S:W.D.S,read:W.D.read,write:W.D.write,ha:W.D.ha,ma:W.D.ma,pa:W.D.pa}},
link:{node:{R:W.B.R,K:W.B.K,ea:W.B.ea},stream:{}},Ya:{node:{R:W.B.R,K:W.B.K},stream:V.wb}});d=V.createNode(a,b,d,e);V.J(d.mode)?(d.B=W.U.dir.node,d.D=W.U.dir.stream,d.C={}):V.isFile(d.mode)?(d.B=W.U.file.node,d.D=W.U.file.stream,d.G=0,d.C=null):V.la(d.mode)?(d.B=W.U.link.node,d.D=W.U.link.stream):V.xa(d.mode)&&(d.B=W.U.Ya.node,d.D=W.U.Ya.stream);d.timestamp=Date.now();a&&(a.C[b]=d,a.timestamp=d.timestamp);return d},qc:function(a){return a.C?a.C.subarray?a.C.subarray(0,a.G):new Uint8Array(a.C):new Uint8Array(0)},
gb:function(a,b){var d=a.C?a.C.length:0;d>=b||(b=Math.max(b,d*(1048576>d?2:1.125)>>>0),0!=d&&(b=Math.max(b,256)),d=a.C,a.C=new Uint8Array(b),0<a.G&&a.C.set(d.subarray(0,a.G),0))},Xb:function(a,b){if(a.G!=b)if(0==b)a.C=null,a.G=0;else{var d=a.C;a.C=new Uint8Array(b);d&&a.C.set(d.subarray(0,Math.min(b,a.G)));a.G=b}},B:{R:function(a){var b={};b.kc=V.xa(a.mode)?a.id:1;b.sc=a.id;b.mode=a.mode;b.Ec=1;b.uid=0;b.rc=0;b.Ba=a.Ba;V.J(a.mode)?b.size=4096:V.isFile(a.mode)?b.size=a.G:V.la(a.mode)?b.size=a.link.length:
b.size=0;b.dc=new Date(a.timestamp);b.Cc=new Date(a.timestamp);b.jc=new Date(a.timestamp);b.ub=4096;b.ec=Math.ceil(b.size/b.ub);return b},K:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&W.Xb(a,b.size)},aa:function(){throw V.Ja[44];},W:function(a,b,d,e){return W.createNode(a,b,d,e)},ra:function(a,b,d){if(V.J(a.mode)){try{var e=V.V(b,d)}catch(g){}if(e)for(var f in e.C)throw new V.A(55);}delete a.parent.C[a.name];a.parent.timestamp=Date.now();
a.name=d;b.C[d]=a;b.timestamp=a.parent.timestamp;a.parent=b},Y:function(a,b){delete a.C[b];a.timestamp=Date.now()},sa:function(a,b){var d=V.V(a,b),e;for(e in d.C)throw new V.A(55);delete a.C[b];a.timestamp=Date.now()},qa:function(a){var b=[".",".."],d;for(d in a.C)a.C.hasOwnProperty(d)&&b.push(d);return b},X:function(a,b,d){a=W.createNode(a,b,41471,0);a.link=d;return a},ea:function(a){if(!V.la(a.mode))throw new V.A(28);return a.link}},D:{read:function(a,b,d,e,f){var g=a.node.C;if(f>=a.node.G)return 0;
a=Math.min(a.node.G-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),d);else for(e=0;e<a;e++)b[d+e]=g[f+e];return a},write:function(a,b,d,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.C||a.C.subarray)){if(g)return a.C=b.subarray(d,d+e),a.G=e;if(0===a.G&&0===f)return a.C=b.slice(d,d+e),a.G=e;if(f+e<=a.G)return a.C.set(b.subarray(d,d+e),f),e}W.gb(a,f+e);if(a.C.subarray&&b.subarray)a.C.set(b.subarray(d,d+e),f);else for(g=0;g<e;g++)a.C[f+g]=b[d+g];a.G=Math.max(a.G,f+e);return e},
S:function(a,b,d){1===d?b+=a.position:2===d&&V.isFile(a.node.mode)&&(b+=a.node.G);if(0>b)throw new V.A(28);return b},ha:function(a,b,d){W.gb(a.node,b+d);a.node.G=Math.max(a.node.G,b+d)},ma:function(a,b,d,e,f,g){if(0!==b)throw new V.A(28);if(!V.isFile(a.node.mode))throw new V.A(43);a=a.node.C;if(g&2||a.buffer!==ua){if(0<e||e+d<a.length)a.subarray?a=a.subarray(e,e+d):a=Array.prototype.slice.call(a,e,e+d);e=!0;z();d=void 0;if(!d)throw new V.A(48);C.set(a,d)}else e=!1,d=a.byteOffset;return{Hc:d,cc:e}},
pa:function(a,b,d,e,f){if(!V.isFile(a.node.mode))throw new V.A(43);if(f&2)return 0;W.D.write(a,b,0,e,d,!1);return 0}}};function Ib(a,b,d){var e="al "+a;ha(a,function(f){na(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&H(e)},function(){if(d)d();else throw'Loading data file "'+a+'" failed.';});e&&Ha(e)}
var V={root:null,oa:[],eb:{},streams:[],Qb:1,T:null,cb:"/",Na:!1,nb:!0,A:null,Ja:{},Fb:null,Ca:0,F:function(a,b){a=U(V.Fa(),a);b=b||{};if(!a)return{path:"",node:null};var d={Ia:!0,Ta:0},e;for(e in d)void 0===b[e]&&(b[e]=d[e]);if(8<b.Ta)throw new V.A(32);a=xb(a.split("/").filter(function(k){return!!k}),!1);var f=V.root;d="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=V.V(f,a[e]);d=T(d,a[e]);V.$(f)&&(!g||g&&b.Ia)&&(f=f.na.root);if(!g||b.P)for(g=0;V.la(f.mode);)if(f=V.ea(d),
d=U(zb(d),f),f=V.F(d,{Ta:b.Ta}).node,40<g++)throw new V.A(32);}return{path:d,node:f}},Z:function(a){for(var b;;){if(V.ya(a))return a=a.H.pb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ma:function(a,b){for(var d=0,e=0;e<b.length;e++)d=(d<<5)-d+b.charCodeAt(e)|0;return(a+d>>>0)%V.T.length},lb:function(a){var b=V.Ma(a.parent.id,a.name);a.ca=V.T[b];V.T[b]=a},mb:function(a){var b=V.Ma(a.parent.id,a.name);if(V.T[b]===a)V.T[b]=a.ca;else for(b=V.T[b];b;){if(b.ca===a){b.ca=a.ca;
break}b=b.ca}},V:function(a,b){var d=V.Nb(a);if(d)throw new V.A(d,a);for(d=V.T[V.Ma(a.id,b)];d;d=d.ca){var e=d.name;if(d.parent.id===a.id&&e===b)return d}return V.aa(a,b)},createNode:function(a,b,d,e){a=new V.sb(a,b,d,e);V.lb(a);return a},Ga:function(a){V.mb(a)},ya:function(a){return a===a.parent},$:function(a){return!!a.na},isFile:function(a){return 32768===(a&61440)},J:function(a){return 16384===(a&61440)},la:function(a){return 40960===(a&61440)},xa:function(a){return 8192===(a&61440)},Kb:function(a){return 24576===
(a&61440)},Lb:function(a){return 4096===(a&61440)},tc:function(a){return 49152===(a&49152)},Gb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Pb:function(a){var b=V.Gb[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},hb:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},da:function(a,b){if(V.nb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Nb:function(a){var b=V.da(a,
"x");return b?b:a.B.aa?0:2},Qa:function(a,b){try{return V.V(a,b),20}catch(d){}return V.da(a,"wx")},za:function(a,b,d){try{var e=V.V(a,b)}catch(f){return f.O}if(a=V.da(a,"wx"))return a;if(d){if(!V.J(e.mode))return 54;if(V.ya(e)||V.Z(e)===V.Fa())return 10}else if(V.J(e.mode))return 31;return 0},Ob:function(a,b){return a?V.la(a.mode)?32:V.J(a.mode)&&("r"!==V.hb(b)||b&512)?31:V.da(a,V.hb(b)):44},tb:4096,Rb:function(a,b){b=b||V.tb;for(a=a||0;a<=b;a++)if(!V.streams[a])return a;throw new V.A(33);},ja:function(a){return V.streams[a]},
Db:function(a,b,d){V.Da||(V.Da=function(){},V.Da.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var e=new V.Da,f;for(f in a)e[f]=a[f];a=e;b=V.Rb(b,d);a.ia=b;return V.streams[b]=a},xb:function(a){V.streams[a]=null},wb:{open:function(a){a.D=V.Ib(a.node.Ba).D;a.D.open&&a.D.open(a)},S:function(){throw new V.A(70);}},Pa:function(a){return a>>8},Ac:function(a){return a&255},ba:function(a,b){return a<<8|b},Ua:function(a,b){V.eb[a]={D:b}},Ib:function(a){return V.eb[a]},
jb:function(a){var b=[];for(a=[a];a.length;){var d=a.pop();b.push(d);a.push.apply(a,d.oa)}return b},rb:function(a,b){function d(k){V.Ca--;return b(k)}function e(k){if(k){if(!e.Eb)return e.Eb=!0,d(k)}else++g>=f.length&&d(null)}"function"===typeof a&&(b=a,a=!1);V.Ca++;1<V.Ca&&x("warning: "+V.Ca+" FS.syncfs operations in flight at once, probably just doing extra work");var f=V.jb(V.root.H),g=0;f.forEach(function(k){if(!k.type.rb)return e(null);k.type.rb(k,a,e)})},H:function(a,b,d){var e="/"===d,f=!d;
if(e&&V.root)throw new V.A(10);if(!e&&!f){var g=V.F(d,{Ia:!1});d=g.path;g=g.node;if(V.$(g))throw new V.A(10);if(!V.J(g.mode))throw new V.A(54);}b={type:a,Gc:b,pb:d,oa:[]};a=a.H(b);a.H=b;b.root=a;e?V.root=a:g&&(g.na=b,g.H&&g.H.oa.push(b));return a},Kc:function(a){a=V.F(a,{Ia:!1});if(!V.$(a.node))throw new V.A(28);a=a.node;var b=a.na,d=V.jb(b);Object.keys(V.T).forEach(function(e){for(e=V.T[e];e;){var f=e.ca;d.includes(e.H)&&V.Ga(e);e=f}});a.na=null;a.H.oa.splice(a.H.oa.indexOf(b),1)},aa:function(a,
b){return a.B.aa(a,b)},W:function(a,b,d){var e=V.F(a,{parent:!0}).node;a=S(a);if(!a||"."===a||".."===a)throw new V.A(28);var f=V.Qa(e,a);if(f)throw new V.A(f);if(!e.B.W)throw new V.A(63);return e.B.W(e,a,b,d)},create:function(a,b){return V.W(a,(void 0!==b?b:438)&4095|32768,0)},M:function(a,b){return V.W(a,(void 0!==b?b:511)&1023|16384,0)},Bc:function(a,b){a=a.split("/");for(var d="",e=0;e<a.length;++e)if(a[e]){d+="/"+a[e];try{V.M(d,b)}catch(f){if(20!=f.O)throw f;}}},Aa:function(a,b,d){"undefined"===
typeof d&&(d=b,b=438);return V.W(a,b|8192,d)},X:function(a,b){if(!U(a))throw new V.A(44);var d=V.F(b,{parent:!0}).node;if(!d)throw new V.A(44);b=S(b);var e=V.Qa(d,b);if(e)throw new V.A(e);if(!d.B.X)throw new V.A(63);return d.B.X(d,b,a)},ra:function(a,b){var d=zb(a),e=zb(b),f=S(a),g=S(b);var k=V.F(a,{parent:!0});var l=k.node;k=V.F(b,{parent:!0});k=k.node;if(!l||!k)throw new V.A(44);if(l.H!==k.H)throw new V.A(75);var m=V.V(l,f);a=Bb(a,e);if("."!==a.charAt(0))throw new V.A(28);a=Bb(b,d);if("."!==a.charAt(0))throw new V.A(55);
try{var n=V.V(k,g)}catch(q){}if(m!==n){b=V.J(m.mode);if(f=V.za(l,f,b))throw new V.A(f);if(f=n?V.za(k,g,b):V.Qa(k,g))throw new V.A(f);if(!l.B.ra)throw new V.A(63);if(V.$(m)||n&&V.$(n))throw new V.A(10);if(k!==l&&(f=V.da(l,"w")))throw new V.A(f);V.mb(m);try{l.B.ra(m,k,g)}catch(q){throw q;}finally{V.lb(m)}}},sa:function(a){var b=V.F(a,{parent:!0}).node;a=S(a);var d=V.V(b,a),e=V.za(b,a,!0);if(e)throw new V.A(e);if(!b.B.sa)throw new V.A(63);if(V.$(d))throw new V.A(10);b.B.sa(b,a);V.Ga(d)},qa:function(a){a=
V.F(a,{P:!0}).node;if(!a.B.qa)throw new V.A(54);return a.B.qa(a)},Y:function(a){var b=V.F(a,{parent:!0}).node;a=S(a);var d=V.V(b,a),e=V.za(b,a,!1);if(e)throw new V.A(e);if(!b.B.Y)throw new V.A(63);if(V.$(d))throw new V.A(10);b.B.Y(b,a);V.Ga(d)},ea:function(a){a=V.F(a).node;if(!a)throw new V.A(44);if(!a.B.ea)throw new V.A(28);return U(V.Z(a.parent),a.B.ea(a))},stat:function(a,b){a=V.F(a,{P:!b}).node;if(!a)throw new V.A(44);if(!a.B.R)throw new V.A(63);return a.B.R(a)},xc:function(a){return V.stat(a,
!0)},ua:function(a,b,d){a="string"===typeof a?V.F(a,{P:!d}).node:a;if(!a.B.K)throw new V.A(63);a.B.K(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},uc:function(a,b){V.ua(a,b,!0)},mc:function(a,b){a=V.ja(a);if(!a)throw new V.A(8);V.ua(a.node,b)},Xa:function(a,b,d,e){a="string"===typeof a?V.F(a,{P:!e}).node:a;if(!a.B.K)throw new V.A(63);a.B.K(a,{timestamp:Date.now()})},vc:function(a,b,d){V.Xa(a,b,d,!0)},nc:function(a,b,d){a=V.ja(a);if(!a)throw new V.A(8);V.Xa(a.node,b,d)},truncate:function(a,b){if(0>
b)throw new V.A(28);a="string"===typeof a?V.F(a,{P:!0}).node:a;if(!a.B.K)throw new V.A(63);if(V.J(a.mode))throw new V.A(31);if(!V.isFile(a.mode))throw new V.A(28);var d=V.da(a,"w");if(d)throw new V.A(d);a.B.K(a,{size:b,timestamp:Date.now()})},pc:function(a,b){a=V.ja(a);if(!a)throw new V.A(8);if(0===(a.flags&2097155))throw new V.A(28);V.truncate(a.node,b)},Mc:function(a,b,d){a=V.F(a,{P:!0}).node;a.B.K(a,{timestamp:Math.max(b,d)})},open:function(a,b,d,e,f){if(""===a)throw new V.A(44);b="string"===typeof b?
V.Pb(b):b;d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var g=a;else{a=yb(a);try{g=V.F(a,{P:!(b&131072)}).node}catch(l){}}var k=!1;if(b&64)if(g){if(b&128)throw new V.A(20);}else g=V.W(a,d,0),k=!0;if(!g)throw new V.A(44);V.xa(g.mode)&&(b&=-513);if(b&65536&&!V.J(g.mode))throw new V.A(54);if(!k&&(d=V.Ob(g,b)))throw new V.A(d);b&512&&V.truncate(g,0);b&=-131713;e=V.Db({node:g,path:V.Z(g),id:g.id,flags:b,mode:g.mode,seekable:!0,position:0,D:g.D,B:g.B,$b:[],error:!1},e,f);e.D.open&&
e.D.open(e);!c.logReadFiles||b&1||(V.Sa||(V.Sa={}),a in V.Sa||(V.Sa[a]=1));return e},close:function(a){if(V.ka(a))throw new V.A(8);a.La&&(a.La=null);try{a.D.close&&a.D.close(a)}catch(b){throw b;}finally{V.xb(a.ia)}a.ia=null},ka:function(a){return null===a.ia},S:function(a,b,d){if(V.ka(a))throw new V.A(8);if(!a.seekable||!a.D.S)throw new V.A(70);if(0!=d&&1!=d&&2!=d)throw new V.A(28);a.position=a.D.S(a,b,d);a.$b=[];return a.position},read:function(a,b,d,e,f){if(0>e||0>f)throw new V.A(28);if(V.ka(a))throw new V.A(8);
if(1===(a.flags&2097155))throw new V.A(8);if(V.J(a.node.mode))throw new V.A(31);if(!a.D.read)throw new V.A(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new V.A(70);b=a.D.read(a,b,d,e,f);g||(a.position+=b);return b},write:function(a,b,d,e,f,g){if(0>e||0>f)throw new V.A(28);if(V.ka(a))throw new V.A(8);if(0===(a.flags&2097155))throw new V.A(8);if(V.J(a.node.mode))throw new V.A(31);if(!a.D.write)throw new V.A(28);a.seekable&&a.flags&1024&&V.S(a,0,2);var k="undefined"!==
typeof f;if(!k)f=a.position;else if(!a.seekable)throw new V.A(70);b=a.D.write(a,b,d,e,f,g);k||(a.position+=b);return b},ha:function(a,b,d){if(V.ka(a))throw new V.A(8);if(0>b||0>=d)throw new V.A(28);if(0===(a.flags&2097155))throw new V.A(8);if(!V.isFile(a.node.mode)&&!V.J(a.node.mode))throw new V.A(43);if(!a.D.ha)throw new V.A(138);a.D.ha(a,b,d)},ma:function(a,b,d,e,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new V.A(2);if(1===(a.flags&2097155))throw new V.A(2);if(!a.D.ma)throw new V.A(43);
return a.D.ma(a,b,d,e,f,g)},pa:function(a,b,d,e,f){return a&&a.D.pa?a.D.pa(a,b,d,e,f):0},Dc:function(){return 0},Oa:function(a,b,d){if(!a.D.Oa)throw new V.A(59);return a.D.Oa(a,b,d)},Ic:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var d,e=V.open(a,b.flags);a=V.stat(a).size;var f=new Uint8Array(a);V.read(e,f,0,a,0);"utf8"===b.encoding?d=B(f,0):"binary"===b.encoding&&(d=f);
V.close(e);return d},Nc:function(a,b,d){d=d||{};d.flags=d.flags||577;a=V.open(a,d.flags,d.mode);if("string"===typeof b){var e=new Uint8Array(ra(b)+1);b=pa(b,e,0,e.length);V.write(a,e,0,b,void 0,d.vb)}else if(ArrayBuffer.isView(b))V.write(a,b,0,b.byteLength,void 0,d.vb);else throw Error("Unsupported data type");V.close(a)},Fa:function(){return V.cb},fc:function(a){a=V.F(a,{P:!0});if(null===a.node)throw new V.A(44);if(!V.J(a.node.mode))throw new V.A(54);var b=V.da(a.node,"x");if(b)throw new V.A(b);
V.cb=a.path},zb:function(){V.M("/tmp");V.M("/home");V.M("/home/web_user")},yb:function(){V.M("/dev");V.Ua(V.ba(1,3),{read:function(){return 0},write:function(b,d,e,f){return f}});V.Aa("/dev/null",V.ba(1,3));Db(V.ba(5,0),Gb);Db(V.ba(6,0),Hb);V.Aa("/dev/tty",V.ba(5,0));V.Aa("/dev/tty1",V.ba(6,0));var a=Ab();V.N("/dev","random",a);V.N("/dev","urandom",a);V.M("/dev/shm");V.M("/dev/shm/tmp")},Bb:function(){V.M("/proc");var a=V.M("/proc/self");V.M("/proc/self/fd");V.H({H:function(){var b=V.createNode(a,
"fd",16895,73);b.B={aa:function(d,e){var f=V.ja(+e);if(!f)throw new V.A(8);d={parent:null,H:{pb:"fake"},B:{ea:function(){return f.path}}};return d.parent=d}};return b}},{},"/proc/self/fd")},Cb:function(){c.stdin?V.N("/dev","stdin",c.stdin):V.X("/dev/tty","/dev/stdin");c.stdout?V.N("/dev","stdout",null,c.stdout):V.X("/dev/tty","/dev/stdout");c.stderr?V.N("/dev","stderr",null,c.stderr):V.X("/dev/tty1","/dev/stderr");V.open("/dev/stdin",0);V.open("/dev/stdout",1);V.open("/dev/stderr",1)},fb:function(){V.A||
(V.A=function(a,b){this.node=b;this.Yb=function(d){this.O=d};this.Yb(a);this.message="FS error"},V.A.prototype=Error(),V.A.prototype.constructor=V.A,[44].forEach(function(a){V.Ja[a]=new V.A(a);V.Ja[a].stack="<generic error, no stack>"}))},Zb:function(){V.fb();V.T=Array(4096);V.H(W,{},"/");V.zb();V.yb();V.Bb();V.Fb={MEMFS:W}},wa:function(a,b,d){V.wa.Na=!0;V.fb();c.stdin=a||c.stdin;c.stdout=b||c.stdout;c.stderr=d||c.stderr;V.Cb()},Wb:function(){V.wa.Na=!1;var a=c._fflush;a&&a(0);for(a=0;a<V.streams.length;a++){var b=
V.streams[a];b&&V.close(b)}},Ka:function(a,b){var d=0;a&&(d|=365);b&&(d|=146);return d},oc:function(a,b){a=V.Ea(a,b);return a.Ha?a.object:null},Ea:function(a,b){try{var d=V.F(a,{P:!b});a=d.path}catch(f){}var e={ya:!1,Ha:!1,error:0,name:null,path:null,object:null,Sb:!1,Ub:null,Tb:null};try{d=V.F(a,{parent:!0}),e.Sb=!0,e.Ub=d.path,e.Tb=d.node,e.name=S(a),d=V.F(a,{P:!b}),e.Ha=!0,e.path=d.path,e.object=d.node,e.name=d.node.name,e.ya="/"===d.path}catch(f){e.error=f.O}return e},$a:function(a,b){a="string"===
typeof a?a:V.Z(a);for(b=b.split("/").reverse();b.length;){var d=b.pop();if(d){var e=T(a,d);try{V.M(e)}catch(f){}a=e}}return e},Ab:function(a,b,d,e,f){a=T("string"===typeof a?a:V.Z(a),b);return V.create(a,V.Ka(e,f))},va:function(a,b,d,e,f,g){a=b?T("string"===typeof a?a:V.Z(a),b):a;e=V.Ka(e,f);f=V.create(a,e);if(d){if("string"===typeof d){a=Array(d.length);b=0;for(var k=d.length;b<k;++b)a[b]=d.charCodeAt(b);d=a}V.ua(f,e|146);a=V.open(f,577);V.write(a,d,0,d.length,0,g);V.close(a);V.ua(f,e)}return f},
N:function(a,b,d,e){a=T("string"===typeof a?a:V.Z(a),b);b=V.Ka(!!d,!!e);V.N.Pa||(V.N.Pa=64);var f=V.ba(V.N.Pa++,0);V.Ua(f,{open:function(g){g.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(g,k,l,m){for(var n=0,q=0;q<m;q++){try{var r=d()}catch(t){throw new V.A(29);}if(void 0===r&&0===n)throw new V.A(6);if(null===r||void 0===r)break;n++;k[l+q]=r}n&&(g.node.timestamp=Date.now());return n},write:function(g,k,l,m){for(var n=0;n<m;n++)try{e(k[l+n])}catch(q){throw new V.A(29);
}m&&(g.node.timestamp=Date.now());return n}});return V.Aa(a,b,f)},ib:function(a){if(a.ob||a.Mb||a.link||a.C)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(fa)try{a.C=Fb(fa(a.url)),a.G=a.C.length}catch(b){throw new V.A(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");
},Za:function(a,b,d,e,f){if("undefined"!==typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";d={ob:!1,url:d};var g=V.Ab(a,b,d,e,f);d.C?g.C=d.C:d.url&&(g.C=null,g.url=d.url);Object.defineProperties(g,{G:{get:function(){return this.C.length}}});var k={};Object.keys(g.D).forEach(function(l){var m=g.D[l];k[l]=function(){V.ib(g);return m.apply(null,arguments)}});k.read=function(l,m,n,q,r){V.ib(g);l=l.node.C;if(r>=
l.length)return 0;q=Math.min(l.length-r,q);if(l.slice)for(var t=0;t<q;t++)m[n+t]=l[r+t];else for(t=0;t<q;t++)m[n+t]=l.get(r+t);return q};g.D=k;return g},ab:function(a,b,d,e,f,g,k,l,m,n){function q(w){function K(qa){n&&n();l||V.va(a,b,qa,e,f,m);g&&g();H(t)}var Z=!1;c.preloadPlugins.forEach(function(qa){!Z&&qa.canHandle(r)&&(qa.handle(w,r,K,function(){k&&k();H(t)}),Z=!0)});Z||K(w)}hb();var r=b?U(T(a,b)):a,t="cp "+r;Ha(t);"string"==typeof d?Ib(d,function(w){q(w)},k):q(d)},indexedDB:function(){return window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Va:function(){return"EM_FS_"+window.location.pathname},Wa:20,ga:"FILE_DATA",Jc:function(a,b,d){b=b||function(){};d=d||function(){};var e=V.indexedDB();try{var f=e.open(V.Va(),V.Wa)}catch(g){return d(g)}f.onupgradeneeded=function(){v("creating db");f.result.createObjectStore(V.ga)};f.onsuccess=function(){var g=f.result.transaction([V.ga],"readwrite"),k=g.objectStore(V.ga),l=0,m=0,n=a.length;a.forEach(function(q){q=k.put(V.Ea(q).object.C,
q);q.onsuccess=function(){l++;l+m==n&&(0==m?b():d())};q.onerror=function(){m++;l+m==n&&(0==m?b():d())}});g.onerror=d};f.onerror=d},wc:function(a,b,d){b=b||function(){};d=d||function(){};var e=V.indexedDB();try{var f=e.open(V.Va(),V.Wa)}catch(g){return d(g)}f.onupgradeneeded=d;f.onsuccess=function(){var g=f.result;try{var k=g.transaction([V.ga],"readonly")}catch(r){d(r);return}var l=k.objectStore(V.ga),m=0,n=0,q=a.length;a.forEach(function(r){var t=l.get(r);t.onsuccess=function(){V.Ea(r).Ha&&V.Y(r);
V.va(zb(r),S(r),t.result,!0,!0,!0);m++;m+n==q&&(0==n?b():d())};t.onerror=function(){n++;m+n==q&&(0==n?b():d())}});k.onerror=d};f.onerror=d}},Jb=void 0;function X(){Jb+=4;return D[Jb-4>>2]}function Y(a){a=V.ja(a);if(!a)throw new V.A(8);return a}c.requestFullscreen=function(a,b){ob(a,b)};c.requestAnimationFrame=function(a){Ta(a)};c.setCanvasSize=function(a,b,d){qb(c.canvas,a,b);d||rb()};c.pauseMainLoop=function(){M=null;Za++};c.resumeMainLoop=function(){Za++;var a=Oa,b=Pa,d=L;L=null;Ya(d);Na(a,b);M()};
c.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};c.createContext=function(a,b,d,e){return lb(a,b,d,e)};function Kb(a,b,d,e){a||(a=this);this.parent=a;this.H=a.H;this.na=null;this.id=V.Qb++;this.name=b;this.mode=d;this.B={};this.D={};this.Ba=e}
Object.defineProperties(Kb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Mb:{get:function(){return V.J(this.mode)}},ob:{get:function(){return V.xa(this.mode)}}});V.sb=Kb;V.Zb();c.FS_createPath=V.$a;c.FS_createDataFile=V.va;c.FS_createPreloadedFile=V.ab;c.FS_createLazyFile=V.Za;c.FS_createDevice=V.N;c.FS_unlink=V.Y;
function Fb(a){var b=Array(ra(a)+1);a=pa(a,b,0,b.length);b.length=a;return b}
var Nb={e:function(a,b,d){Jb=d;try{var e=Y(a);switch(b){case 0:var f=X();return 0>f?-28:V.open(e.path,e.flags,0,f).ia;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=X(),e.flags|=f,0;case 12:return f=X(),wa[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return D[Lb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof V&&g instanceof V.A||z(g),-g.O}},o:function(a,b,d){Jb=d;try{var e=Y(a);switch(b){case 21509:case 21505:return e.I?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.I?
0:-59;case 21519:if(!e.I)return-59;var f=X();return D[f>>2]=0;case 21520:return e.I?-28:-59;case 21531:return f=X(),V.Oa(e,b,f);case 21523:return e.I?0:-59;case 21524:return e.I?0:-59;default:z("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof V&&g instanceof V.A||z(g),-g.O}},g:function(a,b,d){Jb=d;try{var e=a?B(va,a,void 0):"",f=d?X():0;return V.open(e,b,f).ia}catch(g){return"undefined"!==typeof V&&g instanceof V.A||z(g),-g.O}},n:function(){throw"longjmp";},j:function(){z("")},l:function(a,
b,d){va.copyWithin(a,b,b+d)},m:function(){z("OOM")},a:function(a){Xa(a)},d:function(a){try{var b=Y(a);V.close(b);return 0}catch(d){return"undefined"!==typeof V&&d instanceof V.A||z(d),d.O}},h:function(a,b,d,e){try{a:{for(var f=Y(a),g=a=0;g<d;g++){var k=D[b+(8*g+4)>>2],l=V.read(f,C,D[b+8*g>>2],k,void 0);if(0>l){var m=-1;break a}a+=l;if(l<k)break}m=a}D[e>>2]=m;return 0}catch(n){return"undefined"!==typeof V&&n instanceof V.A||z(n),n.O}},k:function(a,b,d,e,f){try{var g=Y(a);a=4294967296*d+(b>>>0);if(-9007199254740992>=
a||9007199254740992<=a)return-61;V.S(g,a,e);Ma=[g.position>>>0,(J=g.position,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];D[f>>2]=Ma[0];D[f+4>>2]=Ma[1];g.La&&0===a&&0===e&&(g.La=null);return 0}catch(k){return"undefined"!==typeof V&&k instanceof V.A||z(k),k.O}},f:function(a,b,d,e){try{a:{for(var f=Y(a),g=a=0;g<d;g++){var k=V.write(f,C,D[b+8*g>>2],D[b+(8*g+4)>>2],void 0);if(0>k){var l=-1;break a}a+=k}l=a}D[e>>2]=l;return 0}catch(m){return"undefined"!==
typeof V&&m instanceof V.A||z(m),m.O}},c:function(){return ka},i:Mb,b:function(a){ka=a}};
(function(){function a(f){c.asm=f.exports;la=c.asm.p;ua=f=la.buffer;c.HEAP8=C=new Int8Array(f);c.HEAP16=wa=new Int16Array(f);c.HEAP32=D=new Int32Array(f);c.HEAPU8=va=new Uint8Array(f);c.HEAPU16=new Uint16Array(f);c.HEAPU32=xa=new Uint32Array(f);c.HEAPF32=new Float32Array(f);c.HEAPF64=new Float64Array(f);ya=c.asm.u;Aa.unshift(c.asm.q);H("wasm-instantiate")}function b(f){a(f.instance)}function d(f){return La().then(function(g){return WebAssembly.instantiate(g,e)}).then(function(g){return g}).then(f,
function(g){x("failed to asynchronously prepare wasm: "+g);z(g)})}var e={a:Nb};Ha("wasm-instantiate");if(c.instantiateWasm)try{return c.instantiateWasm(e,a)}catch(f){return x("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||"function"!==typeof fetch?d(b):fetch(I,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){x("wasm streaming compile failed: "+
g);x("falling back to ArrayBuffer instantiation");return d(b)})})})().catch(ba);return{}})();c.___wasm_call_ctors=function(){return(c.___wasm_call_ctors=c.asm.q).apply(null,arguments)};c._fflush=function(){return(c._fflush=c.asm.r).apply(null,arguments)};var Lb=c.___errno_location=function(){return(Lb=c.___errno_location=c.asm.s).apply(null,arguments)};c._main=function(){return(c._main=c.asm.t).apply(null,arguments)};
var Ob=c.stackSave=function(){return(Ob=c.stackSave=c.asm.v).apply(null,arguments)},Pb=c.stackRestore=function(){return(Pb=c.stackRestore=c.asm.w).apply(null,arguments)},ta=c.stackAlloc=function(){return(ta=c.stackAlloc=c.asm.x).apply(null,arguments)},Qb=c._setThrew=function(){return(Qb=c._setThrew=c.asm.y).apply(null,arguments)};function Mb(a,b,d){var e=Ob();try{return vb(a)(b,d)}catch(f){Pb(e);if(f!==f+0&&"longjmp"!==f)throw f;Qb(1,0)}}c.addRunDependency=Ha;c.removeRunDependency=H;
c.FS_createPath=V.$a;c.FS_createDataFile=V.va;c.FS_createPreloadedFile=V.ab;c.FS_createLazyFile=V.Za;c.FS_createDevice=V.N;c.FS_unlink=V.Y;c.FS=V;var Rb;function Va(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}G=function Sb(){Rb||Tb();Rb||(G=Sb)};
function Tb(a){function b(){if(!Rb&&(Rb=!0,c.calledRun=!0,!A)){c.noFSInit||V.wa.Na||V.wa();V.nb=!1;ub(Aa);ub(Ba);aa(c);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(Ub){var d=a,e=c._main;d=d||[];var f=d.length+1,g=ta(4*(f+1));D[g>>2]=sa(da);for(var k=1;k<f;k++)D[(g>>2)+k]=sa(d[k-1]);D[(g>>2)+f]=0;try{var l=e(f,g);Xa(l)}catch(m){Ua(m)}finally{}}if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;)d=c.postRun.shift(),Da.unshift(d);ub(Da)}}a=a||ca;if(!(0<F)){if(c.preRun)for("function"==
typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Fa();ub(za);0<F||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);b()},1)):b())}}c.run=Tb;function Xa(a){ma=a;noExitRuntime||0<E||(ub(Ca),V.Wb(),Ea=!0);ma=a;if(!(noExitRuntime||0<E)){if(c.onExit)c.onExit(a);A=!0}ea(a,new Va(a))}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var Ub=!0;c.noInitialRun&&(Ub=!1);Tb();


  return npiet.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = npiet;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return npiet; });
else if (typeof exports === 'object')
  exports["npiet"] = npiet;
