
var npiet = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(npiet) {
  npiet = npiet || {};


var c;c||(c=typeof npiet !== 'undefined' ? npiet : {});var aa,ba;c.ready=new Promise(function(a,b){aa=a;ba=b});var h={},p;for(p in c)c.hasOwnProperty(p)&&(h[p]=c[p]);var ca=[],ea="./this.program";function fa(a,b){throw b;}var u="",ha,ia;"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src);_scriptDir&&(u=_scriptDir);0!==u.indexOf("blob:")?u=u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):u="";
ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};ia=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)};var v=c.print||console.log.bind(console),x=c.printErr||console.warn.bind(console);for(p in h)h.hasOwnProperty(p)&&(c[p]=h[p]);h=null;c.arguments&&(ca=c.arguments);c.thisProgram&&(ea=c.thisProgram);c.quit&&(fa=c.quit);
function ja(a){ka||(ka={});ka[a]||(ka[a]=1,x(a))}var ka,la=0,y;c.wasmBinary&&(y=c.wasmBinary);var noExitRuntime=c.noExitRuntime||!1;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ma,A=!1,na;function oa(a,b){a||z("Assertion failed: "+b)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function B(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&pa)return pa.decode(a.subarray(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}
function qa(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(d>=e)break;b[d++]=k}else{if(2047>=k){if(d+1>=e)break;b[d++]=192|k>>6}else{if(65535>=k){if(d+2>=e)break;b[d++]=224|k>>12}else{if(d+3>=e)break;b[d++]=240|k>>18;b[d++]=128|k>>12&63}b[d++]=128|k>>6&63}b[d++]=128|k&63}}b[d]=0;return d-f}
function ra(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function sa(a){var b=ra(a)+1,d=ta(b);qa(a,C,d,b);return d}var va,C,wa,xa,D,ya,za,Aa=[],Ba=[],Ca=[],Da=[],Ea=[],Fa=!1,E=0;function Ga(){var a=c.preRun.shift();Aa.unshift(a)}var F=0,Ha=null,G=null;function Ia(){F++;c.monitorRunDependencies&&c.monitorRunDependencies(F)}
function H(){F--;c.monitorRunDependencies&&c.monitorRunDependencies(F);if(0==F&&(null!==Ha&&(clearInterval(Ha),Ha=null),G)){var a=G;G=null;a()}}c.preloadedImages={};c.preloadedAudios={};function z(a){if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";x(a);A=!0;na=1;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ja(){return I.startsWith("data:application/octet-stream;base64,")}var I;
if(c.locateFile){if(I="npiet-min-es6.wasm",!Ja()){var Ka=I;I=c.locateFile?c.locateFile(Ka,u):u+Ka}}else I=(new URL("npiet-min-es6.wasm",import.meta.url)).toString();function La(){var a=I;try{if(a==I&&y)return new Uint8Array(y);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ma(){return y||"function"!==typeof fetch?Promise.resolve().then(function(){return La()}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return La()})}var J,Na;
function Oa(a,b){Pa=a;Qa=b;if(K)if(Ra||(E+=1,Ra=!0),0==a)L=function(){var e=Math.max(0,Sa+b-Ta())|0;setTimeout(M,e)};else if(1==a)L=function(){Ua(M)};else if(2==a){if("undefined"===typeof setImmediate){var d=[];addEventListener("message",function(e){if("setimmediate"===e.data||"setimmediate"===e.data.target)e.stopPropagation(),d.shift()()},!0);setImmediate=function(e){d.push(e);postMessage("setimmediate","*")}}L=function(){setImmediate(M)}}}var Ta;Ta=function(){return performance.now()};
function Va(a){a instanceof Wa||"unwind"==a||fa(1,a)}function Xa(){if(!(noExitRuntime||0<E))try{Ya(na)}catch(a){Va(a)}}
function Za(a){function b(){return d<$a?(--E,Xa(),!1):!0}oa(!K,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");K=a;var d=$a;Ra=!1;M=function(){if(!A)if(0<ab.length){var e=Date.now(),f=ab.shift();f.Mb(f.ya);if(bb){var g=bb,k=0==g%1?g-1:Math.floor(g);bb=f.mc?k:(8*g+(k+.5))/9}v('main loop blocker "'+f.name+'" took '+(Date.now()-e)+" ms");c.setStatus&&(e=c.statusMessage||
"Please wait...",f=bb,g=cb.qc,f?f<g?c.setStatus(e+" ("+(g-f)+"/"+g+")"):c.setStatus(e):c.setStatus(""));b()&&setTimeout(M,0)}else b()&&(db=db+1|0,1==Pa&&1<Qa&&0!=db%Qa?L():(0==Pa&&(Sa=Ta()),A||c.preMainLoop&&!1===c.preMainLoop()||(eb(a),c.postMainLoop&&c.postMainLoop()),b()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.$b&&SDL.audio.$b(),L())))}}function eb(a){if(!Fa&&!A)try{a(),Xa()}catch(b){Va(b)}}function fb(a){E+=1;setTimeout(function(){--E;eb(a)},1E4)}
var Ra=!1,L=null,$a=0,K=null,Pa=0,Qa=0,db=0,ab=[],cb={},Sa,M,bb,gb=!1,hb=!1,ib=[];
function jb(){function a(){hb=document.pointerLockElement===c.canvas||document.mozPointerLockElement===c.canvas||document.webkitPointerLockElement===c.canvas||document.msPointerLockElement===c.canvas}c.preloadPlugins||(c.preloadPlugins=[]);if(!kb){kb=!0;try{lb=!0}catch(d){lb=!1,v("warning: no blob constructor, cannot create blobs with mimetypes")}mb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:lb?null:v("warning: no BlobBuilder");nb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;c.vb||"undefined"!==typeof nb||(v("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),c.vb=!0);c.preloadPlugins.push({canHandle:function(d){return!c.vb&&/\.(jpg|jpeg|png|bmp)$/i.test(d)},handle:function(d,e,f,g){var k=null;if(lb)try{k=new Blob([d],{type:ob(e)}),k.size!==d.length&&(k=new Blob([(new Uint8Array(d)).buffer],{type:ob(e)}))}catch(n){ja("Blob constructor present but fails: "+
n+"; falling back to blob builder")}k||(k=new mb,k.append((new Uint8Array(d)).buffer),k=k.getBlob());var l=nb.createObjectURL(k),m=new Image;m.onload=function(){oa(m.complete,"Image "+e+" could not be decoded");var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,0,0);c.preloadedImages[e]=n;nb.revokeObjectURL(l);f&&f(d)};m.onerror=function(){v("Image "+l+" could not be decoded");g&&g()};m.src=l}});c.preloadPlugins.push({canHandle:function(d){return!c.Kc&&
d.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(d,e,f,g){function k(q){m||(m=!0,c.preloadedAudios[e]=q,f&&f(d))}function l(){m||(m=!0,c.preloadedAudios[e]=new Audio,g&&g())}var m=!1;if(lb){try{var n=new Blob([d],{type:ob(e)})}catch(q){return l()}n=nb.createObjectURL(n);var r=new Audio;r.addEventListener("canplaythrough",function(){k(r)},!1);r.onerror=function(){if(!m){v("warning: browser could not fully decode audio "+e+", trying slower base64 approach");for(var q="",t=0,w=0,O=0;O<d.length;O++)for(t=
t<<8|d[O],w+=8;6<=w;){var da=t>>w-6&63;w-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[da]}2==w?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],q+="=="):4==w&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],q+="=");r.src="data:audio/x-"+e.substr(-3)+";base64,"+q;k(r)}};r.src=n;fb(function(){k(r)})}else return l()}});var b=c.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),c.elementPointerLock&&b.addEventListener("click",
function(d){!hb&&c.canvas.requestPointerLock&&(c.canvas.requestPointerLock(),d.preventDefault())},!1))}}
function pb(a,b,d,e){if(b&&c.hb&&a==c.canvas)return c.hb;var f;if(b){var g={antialias:!1,alpha:!1,Dc:1};if(e)for(var k in e)g[k]=e[k];if("undefined"!==typeof GL&&(f=GL.nc(a,g)))var l=GL.getContext(f).hc}else l=a.getContext("2d");if(!l)return null;d&&(b||oa("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),c.hb=l,b&&GL.Ec(f),c.Qc=b,ib.forEach(function(m){m()}),jb());return l}var qb=!1,rb=void 0,N=void 0;
function sb(a,b){function d(){gb=!1;var g=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(e.exitFullscreen=tb,rb&&e.requestPointerLock(),gb=!0,N?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=ya[SDL.screen>>2]|8388608),ub(c.canvas),vb()):ub(e)):(g.parentNode.insertBefore(e,g),g.parentNode.removeChild(g),N?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=ya[SDL.screen>>2]&
-8388609),ub(c.canvas),vb()):ub(e));if(c.onFullScreen)c.onFullScreen(gb);if(c.onFullscreen)c.onFullscreen(gb)}rb=a;N=b;"undefined"===typeof rb&&(rb=!0);"undefined"===typeof N&&(N=!1);var e=c.canvas;qb||(qb=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);
f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function tb(){if(!gb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var wb=0;function Ua(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===wb)wb=b+1E3/60;else for(;b+2>=wb;)wb+=1E3/60;setTimeout(a,Math.max(wb-b,0))}}
function ob(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var xb=[];function vb(){var a=c.canvas;xb.forEach(function(b){b(a.width,a.height)})}
function ub(a,b,d){b&&d?(a.fc=b,a.Ob=d):(b=a.fc,d=a.Ob);var e=b,f=d;c.forcedAspectRatio&&0<c.forcedAspectRatio&&(e/f<c.forcedAspectRatio?e=Math.round(f*c.forcedAspectRatio):f=Math.round(e/c.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*
g)}N?(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=d&&(a.height=d),"undefined"!=typeof a.style&&(e!=b||f!=d?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var kb,lb,mb,nb;
function yb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(c);else{var d=b.Mb;"number"===typeof d?void 0===b.ya?P(d)():P(d)(b.ya):d(void 0===b.ya?null:b.ya)}}}var zb=[];function P(a){var b=zb[a];b||(a>=zb.length&&(zb.length=a+1),zb[a]=b=za.get(a));return b}function Ab(a,b){for(var d=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),d++):d&&(a.splice(e,1),d--)}if(b)for(;d;d--)a.unshift("..");return a}
function Bb(a){var b="/"===a.charAt(0),d="/"===a.substr(-1);(a=Ab(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&d&&(a+="/");return(b?"/":"")+a}function Cb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Q(a){if("/"===a)return"/";a=Bb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function R(a,b){return Bb(a+"/"+b)}function Db(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){z("randomDevice")}}
function S(){for(var a="",b=!1,d=arguments.length-1;-1<=d&&!b;d--){b=0<=d?arguments[d]:T.Ka();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ab(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function Eb(a,b){function d(k){for(var l=0;l<k.length&&""===k[l];l++);for(var m=k.length-1;0<=m&&""===k[m];m--);return l>m?[]:k.slice(l,m-l+1)}a=S(a).substr(1);b=S(b).substr(1);a=d(a.split("/"));b=d(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var Fb=[];function Gb(a,b){Fb[a]={input:[],R:[],ka:b};T.Za(a,Hb)}
var Hb={open:function(a){var b=Fb[a.node.Ga];if(!b)throw new T.G(43);a.N=b;a.seekable=!1},close:function(a){a.N.ka.flush(a.N)},flush:function(a){a.N.ka.flush(a.N)},read:function(a,b,d,e){if(!a.N||!a.N.ka.pb)throw new T.G(60);for(var f=0,g=0;g<e;g++){try{var k=a.N.ka.pb(a.N)}catch(l){throw new T.G(29);}if(void 0===k&&0===f)throw new T.G(6);if(null===k||void 0===k)break;f++;b[d+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){if(!a.N||!a.N.ka.Wa)throw new T.G(60);try{for(var f=
0;f<e;f++)a.N.ka.Wa(a.N,b[d+f])}catch(g){throw new T.G(29);}e&&(a.node.timestamp=Date.now());return f}},Jb={pb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ib(b)}return a.input.shift()},Wa:function(a,b){null===b||10===b?(v(B(a.R,0)),a.R=[]):0!=b&&a.R.push(b)},flush:function(a){a.R&&0<a.R.length&&(v(B(a.R,
0)),a.R=[])}},Kb={Wa:function(a,b){null===b||10===b?(x(B(a.R,0)),a.R=[]):0!=b&&a.R.push(b)},flush:function(a){a.R&&0<a.R.length&&(x(B(a.R,0)),a.R=[])}},U={Z:null,M:function(){return U.createNode(null,"/",16895,0)},createNode:function(a,b,d,e){if(T.Pb(d)||T.Qb(d))throw new T.G(63);U.Z||(U.Z={dir:{node:{W:U.H.W,P:U.H.P,fa:U.H.fa,aa:U.H.aa,wa:U.H.wa,ca:U.H.ca,xa:U.H.xa,va:U.H.va,ba:U.H.ba},stream:{X:U.J.X}},file:{node:{W:U.H.W,P:U.H.P},stream:{X:U.J.X,read:U.J.read,write:U.J.write,ma:U.J.ma,ra:U.J.ra,
ua:U.J.ua}},link:{node:{W:U.H.W,P:U.H.P,ja:U.H.ja},stream:{}},cb:{node:{W:U.H.W,P:U.H.P},stream:T.Bb}});d=T.createNode(a,b,d,e);T.O(d.mode)?(d.H=U.Z.dir.node,d.J=U.Z.dir.stream,d.I={}):T.isFile(d.mode)?(d.H=U.Z.file.node,d.J=U.Z.file.stream,d.L=0,d.I=null):T.qa(d.mode)?(d.H=U.Z.link.node,d.J=U.Z.link.stream):T.Ca(d.mode)&&(d.H=U.Z.cb.node,d.J=U.Z.cb.stream);d.timestamp=Date.now();a&&(a.I[b]=d,a.timestamp=d.timestamp);return d},vc:function(a){return a.I?a.I.subarray?a.I.subarray(0,a.L):new Uint8Array(a.I):
new Uint8Array(0)},lb:function(a,b){var d=a.I?a.I.length:0;d>=b||(b=Math.max(b,d*(1048576>d?2:1.125)>>>0),0!=d&&(b=Math.max(b,256)),d=a.I,a.I=new Uint8Array(b),0<a.L&&a.I.set(d.subarray(0,a.L),0))},bc:function(a,b){if(a.L!=b)if(0==b)a.I=null,a.L=0;else{var d=a.I;a.I=new Uint8Array(b);d&&a.I.set(d.subarray(0,Math.min(b,a.L)));a.L=b}},H:{W:function(a){var b={};b.pc=T.Ca(a.mode)?a.id:1;b.xc=a.id;b.mode=a.mode;b.Jc=1;b.uid=0;b.wc=0;b.Ga=a.Ga;T.O(a.mode)?b.size=4096:T.isFile(a.mode)?b.size=a.L:T.qa(a.mode)?
b.size=a.link.length:b.size=0;b.jc=new Date(a.timestamp);b.Hc=new Date(a.timestamp);b.oc=new Date(a.timestamp);b.zb=4096;b.kc=Math.ceil(b.size/b.zb);return b},P:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.bc(a,b.size)},fa:function(){throw T.Oa[44];},aa:function(a,b,d,e){return U.createNode(a,b,d,e)},wa:function(a,b,d){if(T.O(a.mode)){try{var e=T.$(b,d)}catch(g){}if(e)for(var f in e.I)throw new T.G(55);}delete a.parent.I[a.name];
a.parent.timestamp=Date.now();a.name=d;b.I[d]=a;b.timestamp=a.parent.timestamp;a.parent=b},ca:function(a,b){delete a.I[b];a.timestamp=Date.now()},xa:function(a,b){var d=T.$(a,b),e;for(e in d.I)throw new T.G(55);delete a.I[b];a.timestamp=Date.now()},va:function(a){var b=[".",".."],d;for(d in a.I)a.I.hasOwnProperty(d)&&b.push(d);return b},ba:function(a,b,d){a=U.createNode(a,b,41471,0);a.link=d;return a},ja:function(a){if(!T.qa(a.mode))throw new T.G(28);return a.link}},J:{read:function(a,b,d,e,f){var g=
a.node.I;if(f>=a.node.L)return 0;a=Math.min(a.node.L-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),d);else for(e=0;e<a;e++)b[d+e]=g[f+e];return a},write:function(a,b,d,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.I||a.I.subarray)){if(g)return a.I=b.subarray(d,d+e),a.L=e;if(0===a.L&&0===f)return a.I=b.slice(d,d+e),a.L=e;if(f+e<=a.L)return a.I.set(b.subarray(d,d+e),f),e}U.lb(a,f+e);if(a.I.subarray&&b.subarray)a.I.set(b.subarray(d,d+e),f);else for(g=0;g<e;g++)a.I[f+g]=b[d+
g];a.L=Math.max(a.L,f+e);return e},X:function(a,b,d){1===d?b+=a.position:2===d&&T.isFile(a.node.mode)&&(b+=a.node.L);if(0>b)throw new T.G(28);return b},ma:function(a,b,d){U.lb(a.node,b+d);a.node.L=Math.max(a.node.L,b+d)},ra:function(a,b,d,e,f,g){if(0!==b)throw new T.G(28);if(!T.isFile(a.node.mode))throw new T.G(43);a=a.node.I;if(g&2||a.buffer!==va){if(0<e||e+d<a.length)a.subarray?a=a.subarray(e,e+d):a=Array.prototype.slice.call(a,e,e+d);e=!0;z();d=void 0;if(!d)throw new T.G(48);C.set(a,d)}else e=
!1,d=a.byteOffset;return{Mc:d,ic:e}},ua:function(a,b,d,e,f){if(!T.isFile(a.node.mode))throw new T.G(43);if(f&2)return 0;U.J.write(a,b,0,e,d,!1);return 0}}};function Lb(a,b,d){var e="al "+a;ia(a,function(f){oa(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&H(e)},function(){if(d)d();else throw'Loading data file "'+a+'" failed.';});e&&Ia(e)}
var T={root:null,ta:[],jb:{},streams:[],Vb:1,Y:null,ib:"/",Sa:!1,sb:!0,G:null,Oa:{},Kb:null,Ha:0,K:function(a,b){a=S(T.Ka(),a);b=b||{};if(!a)return{path:"",node:null};var d={Na:!0,Ya:0},e;for(e in d)void 0===b[e]&&(b[e]=d[e]);if(8<b.Ya)throw new T.G(32);a=Ab(a.split("/").filter(function(k){return!!k}),!1);var f=T.root;d="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=T.$(f,a[e]);d=R(d,a[e]);T.ea(f)&&(!g||g&&b.Na)&&(f=f.sa.root);if(!g||b.V)for(g=0;T.qa(f.mode);)if(f=T.ja(d),
d=S(Cb(d),f),f=T.K(d,{Ya:b.Ya}).node,40<g++)throw new T.G(32);}return{path:d,node:f}},da:function(a){for(var b;;){if(T.Da(a))return a=a.M.ub,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ra:function(a,b){for(var d=0,e=0;e<b.length;e++)d=(d<<5)-d+b.charCodeAt(e)|0;return(a+d>>>0)%T.Y.length},qb:function(a){var b=T.Ra(a.parent.id,a.name);a.ha=T.Y[b];T.Y[b]=a},rb:function(a){var b=T.Ra(a.parent.id,a.name);if(T.Y[b]===a)T.Y[b]=a.ha;else for(b=T.Y[b];b;){if(b.ha===a){b.ha=a.ha;
break}b=b.ha}},$:function(a,b){var d=T.Sb(a);if(d)throw new T.G(d,a);for(d=T.Y[T.Ra(a.id,b)];d;d=d.ha){var e=d.name;if(d.parent.id===a.id&&e===b)return d}return T.fa(a,b)},createNode:function(a,b,d,e){a=new T.xb(a,b,d,e);T.qb(a);return a},La:function(a){T.rb(a)},Da:function(a){return a===a.parent},ea:function(a){return!!a.sa},isFile:function(a){return 32768===(a&61440)},O:function(a){return 16384===(a&61440)},qa:function(a){return 40960===(a&61440)},Ca:function(a){return 8192===(a&61440)},Pb:function(a){return 24576===
(a&61440)},Qb:function(a){return 4096===(a&61440)},yc:function(a){return 49152===(a&49152)},Lb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Ub:function(a){var b=T.Lb[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},mb:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},ia:function(a,b){if(T.sb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Sb:function(a){var b=T.ia(a,
"x");return b?b:a.H.fa?0:2},Va:function(a,b){try{return T.$(a,b),20}catch(d){}return T.ia(a,"wx")},Ea:function(a,b,d){try{var e=T.$(a,b)}catch(f){return f.U}if(a=T.ia(a,"wx"))return a;if(d){if(!T.O(e.mode))return 54;if(T.Da(e)||T.da(e)===T.Ka())return 10}else if(T.O(e.mode))return 31;return 0},Tb:function(a,b){return a?T.qa(a.mode)?32:T.O(a.mode)&&("r"!==T.mb(b)||b&512)?31:T.ia(a,T.mb(b)):44},yb:4096,Wb:function(a,b){b=b||T.yb;for(a=a||0;a<=b;a++)if(!T.streams[a])return a;throw new T.G(33);},oa:function(a){return T.streams[a]},
Ib:function(a,b,d){T.Ia||(T.Ia=function(){},T.Ia.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var e=new T.Ia,f;for(f in a)e[f]=a[f];a=e;b=T.Wb(b,d);a.na=b;return T.streams[b]=a},Cb:function(a){T.streams[a]=null},Bb:{open:function(a){a.J=T.Nb(a.node.Ga).J;a.J.open&&a.J.open(a)},X:function(){throw new T.G(70);}},Ua:function(a){return a>>8},Fc:function(a){return a&255},ga:function(a,b){return a<<8|b},Za:function(a,b){T.jb[a]={J:b}},Nb:function(a){return T.jb[a]},
ob:function(a){var b=[];for(a=[a];a.length;){var d=a.pop();b.push(d);a.push.apply(a,d.ta)}return b},wb:function(a,b){function d(k){T.Ha--;return b(k)}function e(k){if(k){if(!e.Jb)return e.Jb=!0,d(k)}else++g>=f.length&&d(null)}"function"===typeof a&&(b=a,a=!1);T.Ha++;1<T.Ha&&x("warning: "+T.Ha+" FS.syncfs operations in flight at once, probably just doing extra work");var f=T.ob(T.root.M),g=0;f.forEach(function(k){if(!k.type.wb)return e(null);k.type.wb(k,a,e)})},M:function(a,b,d){var e="/"===d,f=!d;
if(e&&T.root)throw new T.G(10);if(!e&&!f){var g=T.K(d,{Na:!1});d=g.path;g=g.node;if(T.ea(g))throw new T.G(10);if(!T.O(g.mode))throw new T.G(54);}b={type:a,Lc:b,ub:d,ta:[]};a=a.M(b);a.M=b;b.root=a;e?T.root=a:g&&(g.sa=b,g.M&&g.M.ta.push(b));return a},Pc:function(a){a=T.K(a,{Na:!1});if(!T.ea(a.node))throw new T.G(28);a=a.node;var b=a.sa,d=T.ob(b);Object.keys(T.Y).forEach(function(e){for(e=T.Y[e];e;){var f=e.ha;d.includes(e.M)&&T.La(e);e=f}});a.sa=null;a.M.ta.splice(a.M.ta.indexOf(b),1)},fa:function(a,
b){return a.H.fa(a,b)},aa:function(a,b,d){var e=T.K(a,{parent:!0}).node;a=Q(a);if(!a||"."===a||".."===a)throw new T.G(28);var f=T.Va(e,a);if(f)throw new T.G(f);if(!e.H.aa)throw new T.G(63);return e.H.aa(e,a,b,d)},create:function(a,b){return T.aa(a,(void 0!==b?b:438)&4095|32768,0)},S:function(a,b){return T.aa(a,(void 0!==b?b:511)&1023|16384,0)},Gc:function(a,b){a=a.split("/");for(var d="",e=0;e<a.length;++e)if(a[e]){d+="/"+a[e];try{T.S(d,b)}catch(f){if(20!=f.U)throw f;}}},Fa:function(a,b,d){"undefined"===
typeof d&&(d=b,b=438);return T.aa(a,b|8192,d)},ba:function(a,b){if(!S(a))throw new T.G(44);var d=T.K(b,{parent:!0}).node;if(!d)throw new T.G(44);b=Q(b);var e=T.Va(d,b);if(e)throw new T.G(e);if(!d.H.ba)throw new T.G(63);return d.H.ba(d,b,a)},wa:function(a,b){var d=Cb(a),e=Cb(b),f=Q(a),g=Q(b);var k=T.K(a,{parent:!0});var l=k.node;k=T.K(b,{parent:!0});k=k.node;if(!l||!k)throw new T.G(44);if(l.M!==k.M)throw new T.G(75);var m=T.$(l,f);a=Eb(a,e);if("."!==a.charAt(0))throw new T.G(28);a=Eb(b,d);if("."!==
a.charAt(0))throw new T.G(55);try{var n=T.$(k,g)}catch(r){}if(m!==n){b=T.O(m.mode);if(f=T.Ea(l,f,b))throw new T.G(f);if(f=n?T.Ea(k,g,b):T.Va(k,g))throw new T.G(f);if(!l.H.wa)throw new T.G(63);if(T.ea(m)||n&&T.ea(n))throw new T.G(10);if(k!==l&&(f=T.ia(l,"w")))throw new T.G(f);T.rb(m);try{l.H.wa(m,k,g)}catch(r){throw r;}finally{T.qb(m)}}},xa:function(a){var b=T.K(a,{parent:!0}).node;a=Q(a);var d=T.$(b,a),e=T.Ea(b,a,!0);if(e)throw new T.G(e);if(!b.H.xa)throw new T.G(63);if(T.ea(d))throw new T.G(10);
b.H.xa(b,a);T.La(d)},va:function(a){a=T.K(a,{V:!0}).node;if(!a.H.va)throw new T.G(54);return a.H.va(a)},ca:function(a){var b=T.K(a,{parent:!0}).node;a=Q(a);var d=T.$(b,a),e=T.Ea(b,a,!1);if(e)throw new T.G(e);if(!b.H.ca)throw new T.G(63);if(T.ea(d))throw new T.G(10);b.H.ca(b,a);T.La(d)},ja:function(a){a=T.K(a).node;if(!a)throw new T.G(44);if(!a.H.ja)throw new T.G(28);return S(T.da(a.parent),a.H.ja(a))},stat:function(a,b){a=T.K(a,{V:!b}).node;if(!a)throw new T.G(44);if(!a.H.W)throw new T.G(63);return a.H.W(a)},
Cc:function(a){return T.stat(a,!0)},za:function(a,b,d){a="string"===typeof a?T.K(a,{V:!d}).node:a;if(!a.H.P)throw new T.G(63);a.H.P(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},zc:function(a,b){T.za(a,b,!0)},rc:function(a,b){a=T.oa(a);if(!a)throw new T.G(8);T.za(a.node,b)},bb:function(a,b,d,e){a="string"===typeof a?T.K(a,{V:!e}).node:a;if(!a.H.P)throw new T.G(63);a.H.P(a,{timestamp:Date.now()})},Ac:function(a,b,d){T.bb(a,b,d,!0)},sc:function(a,b,d){a=T.oa(a);if(!a)throw new T.G(8);T.bb(a.node,
b,d)},truncate:function(a,b){if(0>b)throw new T.G(28);a="string"===typeof a?T.K(a,{V:!0}).node:a;if(!a.H.P)throw new T.G(63);if(T.O(a.mode))throw new T.G(31);if(!T.isFile(a.mode))throw new T.G(28);var d=T.ia(a,"w");if(d)throw new T.G(d);a.H.P(a,{size:b,timestamp:Date.now()})},uc:function(a,b){a=T.oa(a);if(!a)throw new T.G(8);if(0===(a.flags&2097155))throw new T.G(28);T.truncate(a.node,b)},Rc:function(a,b,d){a=T.K(a,{V:!0}).node;a.H.P(a,{timestamp:Math.max(b,d)})},open:function(a,b,d,e,f){if(""===
a)throw new T.G(44);b="string"===typeof b?T.Ub(b):b;d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Bb(a);try{g=T.K(a,{V:!(b&131072)}).node}catch(l){}}var k=!1;if(b&64)if(g){if(b&128)throw new T.G(20);}else g=T.aa(a,d,0),k=!0;if(!g)throw new T.G(44);T.Ca(g.mode)&&(b&=-513);if(b&65536&&!T.O(g.mode))throw new T.G(54);if(!k&&(d=T.Tb(g,b)))throw new T.G(d);b&512&&T.truncate(g,0);b&=-131713;e=T.Ib({node:g,path:T.da(g),id:g.id,flags:b,mode:g.mode,seekable:!0,position:0,
J:g.J,H:g.H,ec:[],error:!1},e,f);e.J.open&&e.J.open(e);!c.logReadFiles||b&1||(T.Xa||(T.Xa={}),a in T.Xa||(T.Xa[a]=1));return e},close:function(a){if(T.pa(a))throw new T.G(8);a.Qa&&(a.Qa=null);try{a.J.close&&a.J.close(a)}catch(b){throw b;}finally{T.Cb(a.na)}a.na=null},pa:function(a){return null===a.na},X:function(a,b,d){if(T.pa(a))throw new T.G(8);if(!a.seekable||!a.J.X)throw new T.G(70);if(0!=d&&1!=d&&2!=d)throw new T.G(28);a.position=a.J.X(a,b,d);a.ec=[];return a.position},read:function(a,b,d,e,
f){if(0>e||0>f)throw new T.G(28);if(T.pa(a))throw new T.G(8);if(1===(a.flags&2097155))throw new T.G(8);if(T.O(a.node.mode))throw new T.G(31);if(!a.J.read)throw new T.G(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new T.G(70);b=a.J.read(a,b,d,e,f);g||(a.position+=b);return b},write:function(a,b,d,e,f,g){if(0>e||0>f)throw new T.G(28);if(T.pa(a))throw new T.G(8);if(0===(a.flags&2097155))throw new T.G(8);if(T.O(a.node.mode))throw new T.G(31);if(!a.J.write)throw new T.G(28);
a.seekable&&a.flags&1024&&T.X(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new T.G(70);b=a.J.write(a,b,d,e,f,g);k||(a.position+=b);return b},ma:function(a,b,d){if(T.pa(a))throw new T.G(8);if(0>b||0>=d)throw new T.G(28);if(0===(a.flags&2097155))throw new T.G(8);if(!T.isFile(a.node.mode)&&!T.O(a.node.mode))throw new T.G(43);if(!a.J.ma)throw new T.G(138);a.J.ma(a,b,d)},ra:function(a,b,d,e,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new T.G(2);if(1===
(a.flags&2097155))throw new T.G(2);if(!a.J.ra)throw new T.G(43);return a.J.ra(a,b,d,e,f,g)},ua:function(a,b,d,e,f){return a&&a.J.ua?a.J.ua(a,b,d,e,f):0},Ic:function(){return 0},Ta:function(a,b,d){if(!a.J.Ta)throw new T.G(59);return a.J.Ta(a,b,d)},Nc:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var d,e=T.open(a,b.flags);a=T.stat(a).size;var f=new Uint8Array(a);T.read(e,f,
0,a,0);"utf8"===b.encoding?d=B(f,0):"binary"===b.encoding&&(d=f);T.close(e);return d},Sc:function(a,b,d){d=d||{};d.flags=d.flags||577;a=T.open(a,d.flags,d.mode);if("string"===typeof b){var e=new Uint8Array(ra(b)+1);b=qa(b,e,0,e.length);T.write(a,e,0,b,void 0,d.Ab)}else if(ArrayBuffer.isView(b))T.write(a,b,0,b.byteLength,void 0,d.Ab);else throw Error("Unsupported data type");T.close(a)},Ka:function(){return T.ib},lc:function(a){a=T.K(a,{V:!0});if(null===a.node)throw new T.G(44);if(!T.O(a.node.mode))throw new T.G(54);
var b=T.ia(a.node,"x");if(b)throw new T.G(b);T.ib=a.path},Eb:function(){T.S("/tmp");T.S("/home");T.S("/home/web_user")},Db:function(){T.S("/dev");T.Za(T.ga(1,3),{read:function(){return 0},write:function(b,d,e,f){return f}});T.Fa("/dev/null",T.ga(1,3));Gb(T.ga(5,0),Jb);Gb(T.ga(6,0),Kb);T.Fa("/dev/tty",T.ga(5,0));T.Fa("/dev/tty1",T.ga(6,0));var a=Db();T.T("/dev","random",a);T.T("/dev","urandom",a);T.S("/dev/shm");T.S("/dev/shm/tmp")},Gb:function(){T.S("/proc");var a=T.S("/proc/self");T.S("/proc/self/fd");
T.M({M:function(){var b=T.createNode(a,"fd",16895,73);b.H={fa:function(d,e){var f=T.oa(+e);if(!f)throw new T.G(8);d={parent:null,M:{ub:"fake"},H:{ja:function(){return f.path}}};return d.parent=d}};return b}},{},"/proc/self/fd")},Hb:function(){c.stdin?T.T("/dev","stdin",c.stdin):T.ba("/dev/tty","/dev/stdin");c.stdout?T.T("/dev","stdout",null,c.stdout):T.ba("/dev/tty","/dev/stdout");c.stderr?T.T("/dev","stderr",null,c.stderr):T.ba("/dev/tty1","/dev/stderr");T.open("/dev/stdin",0);T.open("/dev/stdout",
1);T.open("/dev/stderr",1)},kb:function(){T.G||(T.G=function(a,b){this.node=b;this.cc=function(d){this.U=d};this.cc(a);this.message="FS error"},T.G.prototype=Error(),T.G.prototype.constructor=T.G,[44].forEach(function(a){T.Oa[a]=new T.G(a);T.Oa[a].stack="<generic error, no stack>"}))},dc:function(){T.kb();T.Y=Array(4096);T.M(U,{},"/");T.Eb();T.Db();T.Gb();T.Kb={MEMFS:U}},Ba:function(a,b,d){T.Ba.Sa=!0;T.kb();c.stdin=a||c.stdin;c.stdout=b||c.stdout;c.stderr=d||c.stderr;T.Hb()},ac:function(){T.Ba.Sa=
!1;var a=c._fflush;a&&a(0);for(a=0;a<T.streams.length;a++){var b=T.streams[a];b&&T.close(b)}},Pa:function(a,b){var d=0;a&&(d|=365);b&&(d|=146);return d},tc:function(a,b){a=T.Ja(a,b);return a.Ma?a.object:null},Ja:function(a,b){try{var d=T.K(a,{V:!b});a=d.path}catch(f){}var e={Da:!1,Ma:!1,error:0,name:null,path:null,object:null,Xb:!1,Zb:null,Yb:null};try{d=T.K(a,{parent:!0}),e.Xb=!0,e.Zb=d.path,e.Yb=d.node,e.name=Q(a),d=T.K(a,{V:!b}),e.Ma=!0,e.path=d.path,e.object=d.node,e.name=d.node.name,e.Da="/"===
d.path}catch(f){e.error=f.U}return e},fb:function(a,b){a="string"===typeof a?a:T.da(a);for(b=b.split("/").reverse();b.length;){var d=b.pop();if(d){var e=R(a,d);try{T.S(e)}catch(f){}a=e}}return e},Fb:function(a,b,d,e,f){a=R("string"===typeof a?a:T.da(a),b);return T.create(a,T.Pa(e,f))},Aa:function(a,b,d,e,f,g){a=b?R("string"===typeof a?a:T.da(a),b):a;e=T.Pa(e,f);f=T.create(a,e);if(d){if("string"===typeof d){a=Array(d.length);b=0;for(var k=d.length;b<k;++b)a[b]=d.charCodeAt(b);d=a}T.za(f,e|146);a=T.open(f,
577);T.write(a,d,0,d.length,0,g);T.close(a);T.za(f,e)}return f},T:function(a,b,d,e){a=R("string"===typeof a?a:T.da(a),b);b=T.Pa(!!d,!!e);T.T.Ua||(T.T.Ua=64);var f=T.ga(T.T.Ua++,0);T.Za(f,{open:function(g){g.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(g,k,l,m){for(var n=0,r=0;r<m;r++){try{var q=d()}catch(t){throw new T.G(29);}if(void 0===q&&0===n)throw new T.G(6);if(null===q||void 0===q)break;n++;k[l+r]=q}n&&(g.node.timestamp=Date.now());return n},write:function(g,
k,l,m){for(var n=0;n<m;n++)try{e(k[l+n])}catch(r){throw new T.G(29);}m&&(g.node.timestamp=Date.now());return n}});return T.Fa(a,b,f)},nb:function(a){if(a.tb||a.Rb||a.link||a.I)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ha)try{a.I=Ib(ha(a.url)),a.L=a.I.length}catch(b){throw new T.G(29);
}else throw Error("Cannot load without read() or XMLHttpRequest.");},eb:function(a,b,d,e,f){if("undefined"!==typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";d={tb:!1,url:d};var g=T.Fb(a,b,d,e,f);d.I?g.I=d.I:d.url&&(g.I=null,g.url=d.url);Object.defineProperties(g,{L:{get:function(){return this.I.length}}});var k={};Object.keys(g.J).forEach(function(l){var m=g.J[l];k[l]=function(){T.nb(g);return m.apply(null,
arguments)}});k.read=function(l,m,n,r,q){T.nb(g);l=l.node.I;if(q>=l.length)return 0;r=Math.min(l.length-q,r);if(l.slice)for(var t=0;t<r;t++)m[n+t]=l[q+t];else for(t=0;t<r;t++)m[n+t]=l.get(q+t);return r};g.J=k;return g},gb:function(a,b,d,e,f,g,k,l,m,n){function r(w){function O(ua){n&&n();l||T.Aa(a,b,ua,e,f,m);g&&g();H(t)}var da=!1;c.preloadPlugins.forEach(function(ua){!da&&ua.canHandle(q)&&(ua.handle(w,q,O,function(){k&&k();H(t)}),da=!0)});da||O(w)}jb();var q=b?S(R(a,b)):a,t="cp "+q;Ia(t);"string"==
typeof d?Lb(d,function(w){r(w)},k):r(d)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},$a:function(){return"EM_FS_"+window.location.pathname},ab:20,la:"FILE_DATA",Oc:function(a,b,d){b=b||function(){};d=d||function(){};var e=T.indexedDB();try{var f=e.open(T.$a(),T.ab)}catch(g){return d(g)}f.onupgradeneeded=function(){v("creating db");f.result.createObjectStore(T.la)};f.onsuccess=function(){var g=f.result.transaction([T.la],"readwrite"),
k=g.objectStore(T.la),l=0,m=0,n=a.length;a.forEach(function(r){r=k.put(T.Ja(r).object.I,r);r.onsuccess=function(){l++;l+m==n&&(0==m?b():d())};r.onerror=function(){m++;l+m==n&&(0==m?b():d())}});g.onerror=d};f.onerror=d},Bc:function(a,b,d){b=b||function(){};d=d||function(){};var e=T.indexedDB();try{var f=e.open(T.$a(),T.ab)}catch(g){return d(g)}f.onupgradeneeded=d;f.onsuccess=function(){var g=f.result;try{var k=g.transaction([T.la],"readonly")}catch(q){d(q);return}var l=k.objectStore(T.la),m=0,n=0,
r=a.length;a.forEach(function(q){var t=l.get(q);t.onsuccess=function(){T.Ja(q).Ma&&T.ca(q);T.Aa(Cb(q),Q(q),t.result,!0,!0,!0);m++;m+n==r&&(0==n?b():d())};t.onerror=function(){n++;m+n==r&&(0==n?b():d())}});k.onerror=d};f.onerror=d}},Mb=void 0;function V(){Mb+=4;return D[Mb-4>>2]}function W(a){a=T.oa(a);if(!a)throw new T.G(8);return a}c.requestFullscreen=function(a,b){sb(a,b)};c.requestAnimationFrame=function(a){Ua(a)};c.setCanvasSize=function(a,b,d){ub(c.canvas,a,b);d||vb()};
c.pauseMainLoop=function(){L=null;$a++};c.resumeMainLoop=function(){$a++;var a=Pa,b=Qa,d=K;K=null;Za(d);Oa(a,b);L()};c.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};c.createContext=function(a,b,d,e){return pb(a,b,d,e)};function Nb(a,b,d,e){a||(a=this);this.parent=a;this.M=a.M;this.sa=null;this.id=T.Vb++;this.name=b;this.mode=d;this.H={};this.J={};this.Ga=e}
Object.defineProperties(Nb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Rb:{get:function(){return T.O(this.mode)}},tb:{get:function(){return T.Ca(this.mode)}}});T.xb=Nb;T.dc();c.FS_createPath=T.fb;c.FS_createDataFile=T.Aa;c.FS_createPreloadedFile=T.gb;c.FS_createLazyFile=T.eb;c.FS_createDevice=T.T;c.FS_unlink=T.ca;
function Ib(a){var b=Array(ra(a)+1);a=qa(a,b,0,b.length);b.length=a;return b}
var Xb={l:function(a,b,d){Mb=d;try{var e=W(a);switch(b){case 0:var f=V();return 0>f?-28:T.open(e.path,e.flags,0,f).na;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=V(),e.flags|=f,0;case 12:return f=V(),xa[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return D[Ob()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof T&&g instanceof T.G||z(g),-g.U}},t:function(a,b,d){Mb=d;try{var e=W(a);switch(b){case 21509:case 21505:return e.N?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.N?
0:-59;case 21519:if(!e.N)return-59;var f=V();return D[f>>2]=0;case 21520:return e.N?-28:-59;case 21531:return f=V(),T.Ta(e,b,f);case 21523:return e.N?0:-59;case 21524:return e.N?0:-59;default:z("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof T&&g instanceof T.G||z(g),-g.U}},n:function(a,b,d){Mb=d;try{var e=a?B(wa,a,void 0):"",f=d?V():0;return T.open(e,b,f).na}catch(g){return"undefined"!==typeof T&&g instanceof T.G||z(g),-g.U}},s:function(){throw"longjmp";},v:function(){z("")},q:function(a,
b,d){wa.copyWithin(a,b,b+d)},r:function(){z("OOM")},d:function(a){Ya(a)},i:function(a){try{var b=W(a);T.close(b);return 0}catch(d){return"undefined"!==typeof T&&d instanceof T.G||z(d),d.U}},u:function(a,b,d,e){try{a:{for(var f=W(a),g=a=0;g<d;g++){var k=D[b+(8*g+4)>>2],l=T.read(f,C,D[b+8*g>>2],k,void 0);if(0>l){var m=-1;break a}a+=l;if(l<k)break}m=a}D[e>>2]=m;return 0}catch(n){return"undefined"!==typeof T&&n instanceof T.G||z(n),n.U}},p:function(a,b,d,e,f){try{var g=W(a);a=4294967296*d+(b>>>0);if(-9007199254740992>=
a||9007199254740992<=a)return-61;T.X(g,a,e);Na=[g.position>>>0,(J=g.position,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];D[f>>2]=Na[0];D[f+4>>2]=Na[1];g.Qa&&0===a&&0===e&&(g.Qa=null);return 0}catch(k){return"undefined"!==typeof T&&k instanceof T.G||z(k),k.U}},m:function(a,b,d,e){try{a:{for(var f=W(a),g=a=0;g<d;g++){var k=T.write(f,C,D[b+8*g>>2],D[b+(8*g+4)>>2],void 0);if(0>k){var l=-1;break a}a+=k}l=a}D[e>>2]=l;return 0}catch(m){return"undefined"!==
typeof T&&m instanceof T.G||z(m),m.U}},b:function(){return la},g:Pb,f:Qb,o:Rb,e:Sb,c:Tb,k:Ub,h:Vb,j:Wb,a:function(a){la=a}};
(function(){function a(f){c.asm=f.exports;ma=c.asm.w;va=f=ma.buffer;c.HEAP8=C=new Int8Array(f);c.HEAP16=xa=new Int16Array(f);c.HEAP32=D=new Int32Array(f);c.HEAPU8=wa=new Uint8Array(f);c.HEAPU16=new Uint16Array(f);c.HEAPU32=ya=new Uint32Array(f);c.HEAPF32=new Float32Array(f);c.HEAPF64=new Float64Array(f);za=c.asm.z;Ba.unshift(c.asm.x);H("wasm-instantiate")}function b(f){a(f.instance)}function d(f){return Ma().then(function(g){return WebAssembly.instantiate(g,e)}).then(function(g){return g}).then(f,
function(g){x("failed to asynchronously prepare wasm: "+g);z(g)})}var e={a:Xb};Ia("wasm-instantiate");if(c.instantiateWasm)try{return c.instantiateWasm(e,a)}catch(f){return x("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||Ja()||"function"!==typeof fetch?d(b):fetch(I,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){x("wasm streaming compile failed: "+
g);x("falling back to ArrayBuffer instantiation");return d(b)})})})().catch(ba);return{}})();c.___wasm_call_ctors=function(){return(c.___wasm_call_ctors=c.asm.x).apply(null,arguments)};c._fflush=function(){return(c._fflush=c.asm.y).apply(null,arguments)};var Ob=c.___errno_location=function(){return(Ob=c.___errno_location=c.asm.A).apply(null,arguments)};c._main=function(){return(c._main=c.asm.B).apply(null,arguments)};
var X=c.stackSave=function(){return(X=c.stackSave=c.asm.C).apply(null,arguments)},Y=c.stackRestore=function(){return(Y=c.stackRestore=c.asm.D).apply(null,arguments)},ta=c.stackAlloc=function(){return(ta=c.stackAlloc=c.asm.E).apply(null,arguments)},Z=c._setThrew=function(){return(Z=c._setThrew=c.asm.F).apply(null,arguments)};function Rb(a,b,d,e,f){var g=X();try{return P(a)(b,d,e,f)}catch(k){Y(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}
function Tb(a,b,d){var e=X();try{P(a)(b,d)}catch(f){Y(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Pb(a,b){var d=X();try{return P(a)(b)}catch(e){Y(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function Sb(a,b){var d=X();try{P(a)(b)}catch(e){Y(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function Qb(a,b,d){var e=X();try{return P(a)(b,d)}catch(f){Y(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}
function Ub(a,b,d,e,f){var g=X();try{P(a)(b,d,e,f)}catch(k){Y(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function Vb(a,b,d,e,f,g){var k=X();try{P(a)(b,d,e,f,g)}catch(l){Y(k);if(l!==l+0&&"longjmp"!==l)throw l;Z(1,0)}}function Wb(a,b,d,e,f,g,k,l,m,n){var r=X();try{P(a)(b,d,e,f,g,k,l,m,n)}catch(q){Y(r);if(q!==q+0&&"longjmp"!==q)throw q;Z(1,0)}}c.addRunDependency=Ia;c.removeRunDependency=H;c.FS_createPath=T.fb;c.FS_createDataFile=T.Aa;c.FS_createPreloadedFile=T.gb;c.FS_createLazyFile=T.eb;
c.FS_createDevice=T.T;c.FS_unlink=T.ca;c.FS=T;var Yb;function Wa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}G=function Zb(){Yb||$b();Yb||(G=Zb)};
function $b(a){function b(){if(!Yb&&(Yb=!0,c.calledRun=!0,!A)){c.noFSInit||T.Ba.Sa||T.Ba();T.sb=!1;yb(Ba);yb(Ca);aa(c);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(ac){var d=a,e=c._main;d=d||[];var f=d.length+1,g=ta(4*(f+1));D[g>>2]=sa(ea);for(var k=1;k<f;k++)D[(g>>2)+k]=sa(d[k-1]);D[(g>>2)+f]=0;try{var l=e(f,g);Ya(l)}catch(m){Va(m)}finally{}}if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;)d=c.postRun.shift(),Ea.unshift(d);yb(Ea)}}a=a||ca;if(!(0<F)){if(c.preRun)for("function"==
typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ga();yb(Aa);0<F||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);b()},1)):b())}}c.run=$b;function Ya(a){na=a;noExitRuntime||0<E||(yb(Da),T.ac(),Fa=!0);na=a;if(!(noExitRuntime||0<E)){if(c.onExit)c.onExit(a);A=!0}fa(a,new Wa(a))}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var ac=!0;c.noInitialRun&&(ac=!1);$b();


  return npiet.ready
}
);
})();
export default npiet;